package com.androidcommondoc.dokka.markdown

import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class HubWriterTest {

    private fun minimalFrontmatter() = FrontmatterFields(
        scope = listOf("api", "sample"),
        sources = listOf("sample"),
        slug = "sample-api-hub",
        layer = "L1",
        description = "sample API hub",
        lastUpdated = "2026-04",
        contentHash = "abc123",
        parent = "api-hub",
    )

    private fun minimalCtx(entries: List<HubEntry> = emptyList()) = HubContext(
        moduleName = "sample",
        entries = entries,
        frontmatter = minimalFrontmatter(),
    )

    @Nested
    inner class Structure {

        @Test
        fun `write_containsFrontmatterBlock`() {
            val result = HubWriter.write(minimalCtx())
            assertTrue(result.contains("---\nscope:"))
        }

        @Test
        fun `write_containsH1WithModuleName`() {
            val result = HubWriter.write(minimalCtx())
            assertTrue(result.contains("# sample API"))
        }

        @Test
        fun `write_containsAutoGeneratedAttribution`() {
            val result = HubWriter.write(minimalCtx())
            assertTrue(result.contains("com.androidcommondoc:dokka-markdown-plugin"))
        }

        @Test
        fun `write_containsSubDocumentsSection`() {
            val result = HubWriter.write(minimalCtx())
            assertTrue(result.contains("## Sub-documents"))
        }

        @Test
        fun `write_containsTableHeader`() {
            val result = HubWriter.write(minimalCtx())
            assertTrue(result.contains("| Class/Interface | Description |"))
            assertTrue(result.contains("|----------------|-------------|"))
        }

        @Test
        fun `write_noTrailingWhitespace`() {
            val result = HubWriter.write(minimalCtx())
            result.lines().forEach { line ->
                assertEquals(line.trimEnd(), line, "Trailing whitespace: [$line]")
            }
        }

        @Test
        fun `write_blankLineAfterTableSeparator`() {
            // RED: production emits entries immediately after "|---|---|" with no blank line
            val entry = HubEntry("MyClass", "-my-class.md", "desc")
            val result = HubWriter.write(minimalCtx(listOf(entry)))
            val lines = result.lines()
            val sepIdx = lines.indexOfFirst { it.startsWith("|---") }
            assertTrue(sepIdx >= 0, "Table separator row not found")
            assertEquals("", lines[sepIdx + 1], "Expected blank line after table separator, got: [${lines[sepIdx + 1]}]")
        }
    }

    @Nested
    inner class Entries {

        @Test
        fun `write_singleEntry_appearsInTable`() {
            val entry = HubEntry("MyClass", "-my-class.md", "Handles something.")
            val result = HubWriter.write(minimalCtx(listOf(entry)))
            assertTrue(result.contains("[MyClass]"))
            assertTrue(result.contains("-my-class.md"))
            assertTrue(result.contains("Handles something."))
        }

        @Test
        fun `write_multipleEntries_sortedAlphabetically`() {
            val entries = listOf(
                HubEntry("Zebra", "zebra.md", "Z"),
                HubEntry("Alpha", "alpha.md", "A"),
                HubEntry("Middle", "middle.md", "M"),
            )
            val result = HubWriter.write(minimalCtx(entries))
            val alphaIdx = result.indexOf("[Alpha]")
            val middleIdx = result.indexOf("[Middle]")
            val zebraIdx = result.indexOf("[Zebra]")
            assertTrue(alphaIdx < middleIdx, "Alpha should come before Middle")
            assertTrue(middleIdx < zebraIdx, "Middle should come before Zebra")
        }

        @Test
        fun `write_entryDescriptionOver80Chars_truncatedTo80`() {
            val longDesc = "A".repeat(100)
            val entry = HubEntry("MyClass", "-my-class.md", longDesc)
            val result = HubWriter.write(minimalCtx(listOf(entry)))
            val tableRow = result.lines().first { it.startsWith("| [MyClass]") }
            val descCol = tableRow.split("|")[2].trim()
            assertTrue(descCol.length <= 80, "Description truncated to 80 chars")
        }

        @Test
        fun `write_entryFileNamePrefixedWithModuleName`() {
            val entry = HubEntry("MyClass", "-my-class.md", "desc")
            val result = HubWriter.write(minimalCtx(listOf(entry)))
            assertTrue(result.contains("sample/-my-class.md"), "Link must include module path")
        }
    }
}
